PROGRAM CSCAN_MOGOD_GPR

!USE MD_BACKGROUND
!USE MD_FFT_HILBERT

IMPLICIT NONE

!USE GSSI_PROGRAM
INCLUDE "IN_OUT_PATH2.h"

INCLUDE "VARIABLES2_500.h"
INCLUDE "AUTO_READ_FILES_500.h"

!INCLUDE "VARIABLES2_250.h"
!INCLUDE "AUTO_READ_FILES_250.h"

OPEN(UNIT=20, FILE=OUTPUT_PATH1, STATUS='REPLACE', ACTION='WRITE')   !A_SCOPE
OPEN(UNIT=21, FILE=OUTPUT_PATH2, STATUS='REPLACE', ACTION='WRITE')   !B_SCAN_IMAGE
OPEN(UNIT=22, FILE=OUTPUT_PATH3, STATUS='REPLACE', ACTION='WRITE')   !C_SCAN_IMAGE
OPEN(UNIT=23, FILE=OUTPUT_PATH4, STATUS='REPLACE', ACTION='WRITE')   !3D_CUBE_IMAGE


!!DO X = 1, DIS
!!   DO Y = 1, TRA
!CALCULATE THE BACKGROUND
!!CALL background(B_SCAN_IMAGE3(X,Y,:),ROWS,300,512,BGR)
!!CALL background(B_SCAN_IMAGE3(X,Y,:),ROWS,300,512,BGR)


!REMOVE THE BACKGROUND
!!     B_SCAN_IMAGE3(X,Y,:) = B_SCAN_IMAGE3(X,Y,:) - BGR
!!   END DO 
!!END DO

!HILBERT TRANSFORM
!HILBERT_A_SCOPE 

!CALL fft_hilbert(B_SCAN_IMAGE3(X,Y,:),ROWS,HILBERT_SIGNAL) 

INCLUDE "OUTPUT_A_B_C_SCOPE.h"

END PROGRAM
