PROGRAM OPEN_GSSI

USE MD_BACKGROUND
USE MD_STACKING
USE MD_DFT_IDFT
USE MD_DFT_HILBERT

IMPLICIT NONE

INCLUDE "IN_OUT_PATH.h"
INCLUDE "VARIABLES_500.h"
INCLUDE "PATH_NAME_OPEN_500.h"
!INCLUDE "VARIABLES_800.h"
!INCLUDE "PATH_NAME_OPEN_800.h"

!======INITIALIZATION=======
DIS = 0
!B_SCAN_IMAGE = 0
!B_SCAN_IMAGE2 = 0.0
!B_SCAN_IMAGE3 = 0.0
!INTENSITY = 0.0
!===========================

PRINT *, "PLEASE TYPE THE DISTANCE"
READ *, DIS

INCLUDE "ALLOCATE.h"

!NO HEADER
READ(10) B_SCAN_IMAGE

!INTEGER => REAL*8
B_SCAN_IMAGE2 = B_SCAN_IMAGE

!ERASE THE UNECESSARY NUMBER. 
!THE NUMBER MEANS THE VALUE OF THE J-1.
!B_SCAN_IMAGE2(1,:) = 0


DO J = 1,DIS
!J=1000
!CALCUATE THE BACKGROUND
    CALL background(B_SCAN_IMAGE2(:,J),ROWS,ROWS-101,ROWS-1,BGR)

!REMOVE THE BACKGROUND

    B_SCAN_IMAGE3(:,J) = B_SCAN_IMAGE2(:,J) - BGR
END DO

!TO MAKE THE GRAPH STABLE
!IF MADE IT 1, IT COULD MAKE AN ERROR WHEN CALCULATING LOG
!THEN, I ASSIGNED 1.
!B_SCAN_IMAGE3(1,:) = 1
!B_SCAN_IMAGE3(2,:) = 1

!STACKING THE A_SCOPE TO SUPPRESS THE BACKGROUND
    CALL stacking(B_SCAN_IMAGE3,ROWS,DIS,STACKED_A_SCOPE)

!DFT
imag = 0.0
    CALL dft(STACKED_A_SCOPE, imag, ROWS, dft_real, dft_imag)
!    CALL dft(B_SCAN_IMAGE3(:,J), imag, ROWS, dft_real, dft_imag)
!    CALL idft(dft_real,dft_imag, ROWS, idft_real, idft_imag)



!HILBERT TRANSFORMATION
J = 3
!HILBERT_A_SCOPE
!    CALL dft_hilbert(B_SCAN_IMAGE3(:,J),ROWS,HILBERT_SIGNAL, a_idft_imag)
!HILBERT_STACKED_A_SCOPE
    CALL dft_hilbert(STACKED_A_SCOPE,ROWS,HILBERT_STACKED_SIGNAL,a_idft_imag)

INCLUDE "OUTPUT_A_SCOPE.h"
INCLUDE "OUTPUT_B_SCAN.h"
INCLUDE "OUTPUT_STACKED_A_SCOPE.h"
INCLUDE "OUTPUT_DFT_STACKED_A_SCOPE.h"
INCLUDE "OUTPUT_HILBERT_A_SCOPE.h"
INCLUDE "OUTPUT_HILBERT_STACKED_A_SCOPE.h"

END PROGRAM
